### ISSUE TITLE
Embedded CLI becomes unresponsive when line buffer is full

### ISSUE THREAD

**Issue by dwhinham** [AndreRenaud/EmbeddedCLI#25]
Thank you for this clean and simple CLI library!

One thing I noticed while testing it, is that when `EMBEDDED_CLI_MAX_LINE - 1` characters are typed into the CLI, the CLI is no longer able to process any further characters (including backspace or movement), putting it into an unrecoverable state.

The range checks in `embedded_cli_insert_char()` probably just need to account for characters that will not increase the usage of the buffer.

**Comment by AndreRenaud** [comment]
Yeah, that's a good point. Can you have a look at https://github.com/AndreRenaud/EmbeddedCLI/pull/26 and see if that helps? It doesn't cover all the cases, but it should at least allow backspacing when full (no cursor moves though)

**Comment by AndreRenaud** [comment]
Actually, I changed it to do the check at the last possible moment (When we actually modify the buffer), which should mean that all manipulations that don't modify the buffer still work. Same PR# - how does that look?

**Comment by dwhinham** [comment]
Thank you for the quick fix, I just tested it and everything seems good as far as I can tell.

LGTM!

**Comment by AndreRenaud** [comment]
Great! I've merged that PR, so I'll close this. Let me know if you have any other issues.

**Comment by dwhinham** [comment]
Perfect, thank you again!
